image:
  repository: ghcr.io/igor-gomes-u/electricity-price
  tag: dev-c2c6c32
  digest: "sha256:9a2a8299eadbe5736a4b9b2faec6c6cb83f5a4472c8de23f12800f30399097c9"

probes:
  startup:
    enabled: true

ingress:
  enabled: true
  className: nginx
  annotations: 
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  hosts:
    - host: dev.electricity-price.local
      paths:
        - path: /
          pathType: Prefix
  tls:
    enabled: true          
    secretName: electricity-price-dev-tls 

networkPolicy:
  enabled: true

serviceMonitor:
  enabled: false

alerts:
  enabled: false


