image:
  repository: ghcr.io/igor-gomes-u/electricity-price
  tag: dev-f670f52
  digest: "sha256:6bdf006a3ee93fd488a515bf8a3fa1eb876eb941f1fd6c7a5014b4eb99077480"

probes:
  startup:
    enabled: true

ingress:
  enabled: true
  className: nginx
  annotations: 
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  hosts:
    - host: dev.electricity-price.local
      paths:
        - path: /
          pathType: Prefix
  tls:
    enabled: true          
    secretName: electricity-price-dev-tls 

networkPolicy:
  enabled: true

serviceMonitor:
  enabled: false

alerts:
  enabled: false


