image:
  repository: ghcr.io/igor-gomes-u/electricity-price
  tag: dev-987255a
  digest: "sha256:b3379ff9190201fcf8d1065f281e9a0d21733c5d60fdbc3c89c477f2c6111c96"

probes:
  startup:
    enabled: true

ingress:
  enabled: true
  className: nginx
  annotations: 
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  hosts:
    - host: dev.electricity-price.local
      paths:
        - path: /
          pathType: Prefix
  tls:
    enabled: true          
    secretName: electricity-price-dev-tls 

networkPolicy:
  enabled: true

serviceMonitor:
  enabled: false

alerts:
  enabled: false


